CREATE TABLE bookings ( 
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
name VARCHAR(30) NOT NULL, 
email VARCHAR(50) NOT NULL, 
phone VARCHAR(20) NOT NULL, 
date DATE NOT NULL, 
Ɵme TIME NOT NULL,
locaƟon VARCHAR(100) NOT NULL,
duraƟon INT(3) NOT NULL
) 
